@startuml ER 

class Student {
    *st_id : INT
    --
    username : STRING
    password : STRING
    email : STRING
    points : INT
}
class Advertisment {
    *ad_id : INT
    --
    date_posted : DATE 
    pick_up_point : LOCATION
    quantity : INT
    path_to_picture : STRING
    allergies : VARCHAR
    state : VARCHAR
}
class Admin {
    *admin_id : INT
    --
    username : STRING
    password : STRING
}
class Request {
    *ad_id : INT
    *con_id : INT
}
class Rating {
    *req_id : INT
    --
    description : TEXT 
}

Student --> Advertisment : posts
Student --> Advertisment : edits
Student --> Advertisment : deletes
Advertisment --> Advertisment : deletes
Student --> Request : files
Request --> Advertisment : allocates
Student --> Request : approves/rejects
Request --> Rating : creates
Student --> Rating : writes
Rating --> Student : penalty
Rating --> Student : rewards
@enduml 